blueprints/frontend_student.py
from flask import Blueprint, session, redirect, url_for

from .nav import render_template
from ._objs import *
from .frontend_user import require_login

frontend_student = Blueprint("frontend_student", __name__)


@frontend_student.route("/student")
@require_login
def index():
    return render_template("student/index.html")


@frontend_student.route("/student/schedule")
@require_login(prev_endpoint="frontend_student.index")
def schedule_appointment():
    return render_template("student/schedule.html")


@frontend_student.route("/student/walkin")
def walk_in_appointment():
    return render_template("student/walkin.html")


@frontend_student.route("/student/message")
def send_message():
    return render_template("student/message.html")

templates/student/index.html
{%- extends "base.html" %}

{% import "bootstrap/utils.html" as utils %}

{% block layout %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='layouts/portal.css') }}">
{% endblock %}

{% block scriptsex %}
{%- endblock %}

{% block titleex -%} Student Portal {%- endblock %}

{% block content %}
<div class="container">
    {%- with messages = get_flashed_messages(with_categories=True) %}
    {%- if messages %}
    <div class="row">
        {{ utils.flashed_messages(messages) }}
    </div>
    {%- endif %}
    {%- endwith %}
    <div class="row">
        <div class="col-md-12 set-center" style="margin-bottom: initial">
            <div class="well">
                <p class="h1-nbs">SCC IE Office People Calling System - Student Index.</p>
                <div class="glyphicon glyphicon-circle-arrow-right">
                    Building.
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-lg-4 set-center">
            <a class="btn btn-primary btn-big btn-func" href="{{ url_for('frontend_student.schedule_appointment') }}">Schedule an Appointment</a>
        </div>
        <div class="col-md-12 col-lg-4 set-center">
            <a class="btn btn-info btn-big btn-func" href="{{ url_for('frontend_student.walk_in_appointment') }}">Walk-in Appointment / Check-in</a>
        </div>
        <div class="col-md-12 col-lg-4 set-center">
            <a class="btn btn-success btn-big btn-func" href="{{ url_for('frontend_student.send_message') }}">Send Message to an Advisor</a>
        </div>
    </div>
</div>
{%- endblock %}

templates/student/message.html
{%- extends "base.html" %}

{% import "bootstrap/utils.html" as utils %}

{% block layout %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='layouts/portal.css') }}">
{% endblock %}

{% block scriptsex %}
{%- endblock %}

{% block titleex -%} Student - Send a Message to Advisor {%- endblock %}

{% block content %}
<div class="container">
    {%- with messages = get_flashed_messages(with_categories=True) %}
    {%- if messages %}
    <div class="row">
        {{ utils.flashed_messages(messages) }}
    </div>
    {%- endif %}
    {%- endwith %}
    <div class="row">
        <div class="col-md-12 set-center" style="margin-bottom: initial">
            <div class="well">
                <p class="h1-nbs">SCC IE Office People Calling System - Student - Send a Message to Advisor</p>
                <div class="glyphicon glyphicon-circle-arrow-right">
                    Building.
                </div>
            </div>
        </div>
    </div>
</div>
{%- endblock %}

templates/student/schedule.html
{%- extends "base.html" %}

{% import "bootstrap/utils.html" as utils %}

{% block layout %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='layouts/portal.css') }}">
{% endblock %}

{% block scriptsex %}
{%- endblock %}

{% block titleex -%} Student - Schedule an Appointment {%- endblock %}

{% block content %}
<div class="container">
    {%- with messages = get_flashed_messages(with_categories=True) %}
    {%- if messages %}
    <div class="row">
        {{ utils.flashed_messages(messages) }}
    </div>
    {%- endif %}
    {%- endwith %}
    <div class="row">
        <div class="col-md-12 set-center" style="margin-bottom: initial">
            <div class="well">
                <p class="h1-nbs">SCC IE Office People Calling System - Student - Schedule an Appointment.</p>
                <div class="glyphicon glyphicon-circle-arrow-right">
                    Building.
                </div>
            </div>
        </div>
    </div>
</div>
{%- endblock %}

templates/student/walkin.html
{%- extends "base.html" %}

{% import "bootstrap/utils.html" as utils %}

{% block layout %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='layouts/portal.css') }}">
{% endblock %}

{% block scriptsex %}
{%- endblock %}

{% block titleex -%} Student - Walk-in Appointment {%- endblock %}

{% block content %}
<div class="container">
    {%- with messages = get_flashed_messages(with_categories=True) %}
    {%- if messages %}
    <div class="row">
        {{ utils.flashed_messages(messages) }}
    </div>
    {%- endif %}
    {%- endwith %}
    <div class="row">
        <div class="col-md-12 set-center" style="margin-bottom: initial">
            <div class="well">
                <p class="h1-nbs">SCC IE Office People Calling System - Student - Walk-in Appointment</p>
                <div class="glyphicon glyphicon-circle-arrow-right">
                    Building.
                </div>
            </div>
        </div>
    </div>
</div>
{%- endblock %}