blueprints/frontend_advisor.py
from flask import Blueprint

from .nav import render_template

frontend_advisor = Blueprint("frontend_advisor", __name__)


@frontend_advisor.route("/advisor")
def index():
    return render_template("advisor/index.html")

blueprints/frontend_staff.py
from flask import Blueprint

from .nav import render_template

frontend_staff = Blueprint("frontend_staff", __name__)


@frontend_staff.route("/staff")
def index():
    return render_template("staff/index.html")

templates/base.html
{%- extends "bootstrap/base.html" %}

{% block title -%} {% block titleex %}{% endblock %} | SCC IE Office ANS {%- endblock %}

{% import "bootstrap/fixes.html" as fixes %}

{% block metas %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="This is the website for IE office in Shoreline CC to manage the adivising queue.">
<meta name="author" content="RaenonX JELLYCAT">
{%- endblock %}

{% block head %}
{{ super() }}
{{ fixes.ie8() }}
{{ JSGlue.include() }}
{% block layout %}{% endblock %}
<link rel="shortcut icon" href="{{ url_for("static", filename="favicon.ico") }}">
{% block headex %}{% endblock %}
{%- endblock %}

{% block scripts %}
{{ super() }}
    <script src="{{ url_for('static', filename='scripts/main.js') }}" type="text/javascript"></script>
{% block scriptsex %}
{% endblock %}
{% endblock %}

{% block styles -%}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for("static", filename="layouts/main.css") }}">
{% block styleex %}{% endblock %}
{% endblock %}

{% block navbar %}
{{ nav.main.render() }}
{% endblock %}

templates/index.html
{%- extends "base.html" %}

{% import "bootstrap/utils.html" as utils %}

{% block layout %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='layouts/portal.css') }}">
{% endblock %}

{% block scriptsex %}
{%- endblock %}

{% block titleex -%} Homepage {%- endblock %}

{% block content %}
<div class="container">
    {%- with messages = get_flashed_messages(with_categories=True) %}
        {%- if messages %}
        <div class="row">
            {{ utils.flashed_messages(messages) }}
        </div>
    {%- endif %}
    {%- endwith %}
    <div class="row">
        <div class="col-md-12 set-center" style="margin-bottom: initial">
            <div class="well">
                <p class="h1-nbs">SCC IE Office People Calling System.</p>
                <div class="glyphicon glyphicon-circle-arrow-right">
                    Building.
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-lg-4 set-center">
            <a class="btn btn-primary btn-big btn-func" href="{{ url_for('frontend_student.index') }}">Student's Portal</a>
        </div>
        <div class="col-md-12 col-lg-4 set-center">
            <a class="btn btn-info btn-big btn-func" href="{{ url_for('frontend_advisor.index') }}">Advisor's Portal</a>
        </div>
        <div class="col-md-12 col-lg-4 set-center">
            <a class="btn btn-success btn-big btn-func" href="{{ url_for('frontend_staff.index') }}">Staff's Portal</a>
        </div>
    </div>
</div>
{%- endblock %}